export const CategoryListData = [
  {
    status: "success",
    statuscode: "200",
    message: "Request processed successfully.",
    data: [
      {
        Id: 1,
        Title: "Essence Mascara Lash Princess",
        Description:
          "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        Category: "beauty",
        Price: 9.99,
        DiscountPercentage: 7.17,
        Rating: 4.94,
        Stock: 5,
        Brand: "Essence",
        Tags: ["beauty", "mascara"],
        Images: [
          "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png",
        ],
      },
      {
        Id: 10,
        Title: "Gucci Bloom Eau de",
        Description:
          "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
        Category: "fragrances",
        Price: 79.99,
        DiscountPercentage: 8.9,
        Rating: 2.69,
        Stock: 93,
        Brand: "Gucci",
        Tags: ["fragrances", "perfumes"],
        Images: [
          "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/1.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/2.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/3.png",
        ],
      },
      {
        Id: 11,
        Title: "Annibale Colombo Bed",
        Description:
          "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
        Category: "furniture",
        Price: 1899.99,
        DiscountPercentage: 0.29,
        Rating: 4.14,
        Stock: 47,
        Brand: "Annibale Colombo",
        Tags: ["furniture", "beds"],
        Images: [
          "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png",
          "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/2.png",
          "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/3.png",
        ],
      },
      {
        Id: 12,
        Title: "Annibale Colombo Sofa",
        Description:
          "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
        Category: "furniture",
        Price: 2499.99,
        DiscountPercentage: 18.54,
        Rating: 3.08,
        Stock: 16,
        Brand: "Annibale Colombo",
        Tags: ["furniture", "sofas"],
        Images: [
          "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png",
          "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/2.png",
          "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/3.png",
        ],
      },
      {
        Id: 13,
        Title: "Bedside Table African Cherry",
        Description:
          "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
        Category: "furniture",
        Price: 299.99,
        DiscountPercentage: 9.58,
        Rating: 4.48,
        Stock: 16,
        Brand: "Furniture Co.",
        Tags: ["furniture", "bedside tables"],
        Images: [
          "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/1.png",
          "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/2.png",
          "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/3.png",
        ],
      },
      {
        Id: 14,
        Title: "Knoll Saarinen Executive Conference Chair",
        Description:
          "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
        Category: "furniture",
        Price: 499.99,
        DiscountPercentage: 15.23,
        Rating: 4.11,
        Stock: 47,
        Brand: "Knoll",
        Tags: ["furniture", "office chairs"],
        Images: [
          "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/1.png",
          "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/2.png",
          "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/3.png",
        ],
      },
      {
        Id: 15,
        Title: "Wooden Bathroom Sink With Mirror",
        Description:
          "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
        Category: "furniture",
        Price: 799.99,
        DiscountPercentage: 11.22,
        Rating: 3.26,
        Stock: 95,
        Brand: "Bath Trends",
        Tags: ["furniture", "bathroom"],
        Images: [
          "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/1.png",
          "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/2.png",
          "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/3.png",
        ],
      },
      {
        Id: 16,
        Title: "Apple",
        Description:
          "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
        Category: "groceries",
        Price: 1.99,
        DiscountPercentage: 1.97,
        Rating: 2.96,
        Stock: 9,
        Brand: "",
        Tags: ["fruits"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Apple/1.png",
        ],
      },
      {
        Id: 17,
        Title: "Beef Steak",
        Description:
          "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
        Category: "groceries",
        Price: 12.99,
        DiscountPercentage: 17.99,
        Rating: 2.83,
        Stock: 96,
        Brand: "",
        Tags: ["meat"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/1.png",
        ],
      },
      {
        Id: 18,
        Title: "Cat Food",
        Description:
          "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
        Category: "groceries",
        Price: 8.99,
        DiscountPercentage: 9.57,
        Rating: 2.88,
        Stock: 13,
        Brand: "",
        Tags: ["pet supplies", "cat food"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/1.png",
        ],
      },
      {
        Id: 19,
        Title: "Chicken Meat",
        Description:
          "Fresh and tender chicken meat, suitable for various culinary preparations.",
        Category: "groceries",
        Price: 9.99,
        DiscountPercentage: 10.46,
        Rating: 4.61,
        Stock: 69,
        Brand: "",
        Tags: ["meat"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/1.png",
          "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/2.png",
        ],
      },
      {
        Id: 2,
        Title: "Eyeshadow Palette with Mirror",
        Description:
          "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
        Category: "beauty",
        Price: 19.99,
        DiscountPercentage: 5.5,
        Rating: 3.28,
        Stock: 44,
        Brand: "Glamour Beauty",
        Tags: ["beauty", "eyeshadow"],
        Images: [
          "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png",
        ],
      },
      {
        Id: 20,
        Title: "Cooking Oil",
        Description:
          "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
        Category: "groceries",
        Price: 4.99,
        DiscountPercentage: 18.89,
        Rating: 4.01,
        Stock: 22,
        Brand: "",
        Tags: ["cooking essentials"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/1.png",
        ],
      },
      {
        Id: 21,
        Title: "Cucumber",
        Description:
          "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
        Category: "groceries",
        Price: 1.49,
        DiscountPercentage: 11.44,
        Rating: 4.71,
        Stock: 22,
        Brand: "",
        Tags: ["vegetables"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png",
        ],
      },
      {
        Id: 22,
        Title: "Dog Food",
        Description:
          "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
        Category: "groceries",
        Price: 10.99,
        DiscountPercentage: 18.15,
        Rating: 2.74,
        Stock: 40,
        Brand: "",
        Tags: ["pet supplies", "dog food"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/1.png",
        ],
      },
      {
        Id: 23,
        Title: "Eggs",
        Description:
          "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
        Category: "groceries",
        Price: 2.99,
        DiscountPercentage: 5.8,
        Rating: 4.46,
        Stock: 10,
        Brand: "",
        Tags: ["dairy"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Eggs/1.png",
        ],
      },
      {
        Id: 24,
        Title: "Fish Steak",
        Description:
          "Quality fish steak, suitable for grilling, baking, or pan-searing.",
        Category: "groceries",
        Price: 14.99,
        DiscountPercentage: 7,
        Rating: 4.83,
        Stock: 99,
        Brand: "",
        Tags: ["seafood"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/1.png",
        ],
      },
      {
        Id: 25,
        Title: "Green Bell Pepper",
        Description:
          "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
        Category: "groceries",
        Price: 1.29,
        DiscountPercentage: 15.5,
        Rating: 4.28,
        Stock: 89,
        Brand: "",
        Tags: ["vegetables"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/1.png",
        ],
      },
      {
        Id: 26,
        Title: "Green Chili Pepper",
        Description:
          "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
        Category: "groceries",
        Price: 0.99,
        DiscountPercentage: 18.51,
        Rating: 4.43,
        Stock: 8,
        Brand: "",
        Tags: ["vegetables"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/1.png",
        ],
      },
      {
        Id: 27,
        Title: "Honey Jar",
        Description:
          "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
        Category: "groceries",
        Price: 6.99,
        DiscountPercentage: 1.91,
        Rating: 3.5,
        Stock: 25,
        Brand: "",
        Tags: ["condiments"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/1.png",
        ],
      },
      {
        Id: 28,
        Title: "Ice Cream",
        Description:
          "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
        Category: "groceries",
        Price: 5.49,
        DiscountPercentage: 7.58,
        Rating: 3.77,
        Stock: 76,
        Brand: "",
        Tags: ["desserts"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/1.png",
          "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/2.png",
          "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/3.png",
          "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/4.png",
        ],
      },
      {
        Id: 29,
        Title: "Juice",
        Description:
          "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
        Category: "groceries",
        Price: 3.99,
        DiscountPercentage: 5.45,
        Rating: 3.41,
        Stock: 99,
        Brand: "",
        Tags: ["beverages"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Juice/1.png",
        ],
      },
      {
        Id: 3,
        Title: "Powder Canister",
        Description:
          "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
        Category: "beauty",
        Price: 14.99,
        DiscountPercentage: 18.14,
        Rating: 3.82,
        Stock: 59,
        Brand: "Velvet Touch",
        Tags: ["beauty", "face powder"],
        Images: [
          "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png",
        ],
      },
      {
        Id: 30,
        Title: "Kiwi",
        Description:
          "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
        Category: "groceries",
        Price: 2.49,
        DiscountPercentage: 10.32,
        Rating: 4.37,
        Stock: 1,
        Brand: "",
        Tags: ["fruits"],
        Images: [
          "https://cdn.dummyjson.com/products/images/groceries/Kiwi/1.png",
        ],
      },
      {
        Id: 4,
        Title: "Red Lipstick",
        Description:
          "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
        Category: "beauty",
        Price: 12.99,
        DiscountPercentage: 19.03,
        Rating: 2.51,
        Stock: 68,
        Brand: "Chic Cosmetics",
        Tags: ["beauty", "lipstick"],
        Images: [
          "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png",
        ],
      },
      {
        Id: 5,
        Title: "Red Nail Polish",
        Description:
          "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
        Category: "beauty",
        Price: 8.99,
        DiscountPercentage: 2.46,
        Rating: 3.91,
        Stock: 71,
        Brand: "Nail Couture",
        Tags: ["beauty", "nail polish"],
        Images: [
          "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png",
        ],
      },
      {
        Id: 6,
        Title: "Calvin Klein CK One",
        Description:
          "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
        Category: "fragrances",
        Price: 49.99,
        DiscountPercentage: 0.32,
        Rating: 4.85,
        Stock: 17,
        Brand: "Calvin Klein",
        Tags: ["fragrances", "perfumes"],
        Images: [
          "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/2.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/3.png",
        ],
      },
      {
        Id: 7,
        Title: "Chanel Coco Noir Eau De",
        Description:
          "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
        Category: "fragrances",
        Price: 129.99,
        DiscountPercentage: 18.64,
        Rating: 2.76,
        Stock: 41,
        Brand: "Chanel",
        Tags: ["fragrances", "perfumes"],
        Images: [
          "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/2.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/3.png",
        ],
      },
      {
        Id: 8,
        Title: "Dior J'adore",
        Description:
          "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
        Category: "fragrances",
        Price: 89.99,
        DiscountPercentage: 17.44,
        Rating: 3.31,
        Stock: 91,
        Brand: "Dior",
        Tags: ["fragrances", "perfumes"],
        Images: [
          "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/2.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/3.png",
        ],
      },
      {
        Id: 9,
        Title: "Dolce Shine Eau de",
        Description:
          "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
        Category: "fragrances",
        Price: 69.99,
        DiscountPercentage: 11.47,
        Rating: 2.68,
        Stock: 3,
        Brand: "Dolce & Gabbana",
        Tags: ["fragrances", "perfumes"],
        Images: [
          "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/1.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/2.png",
          "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/3.png",
        ],
      },
    ],
  },
];
